#!/bin/bash


if [[ $# -ne 0 ]]; then
    echo "Usage: ./push"
    exit 0
fi
echo hi
DEPOT_SERVER=""

SSID=""
if [ `uname -s` == 'Darwin' ]; then
    SSID=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | grep ' SSID' | awk -F': ' '{print $2}')
else
    echo SSID detection on linux machines not handled yet.
    exit
fi

ping -c1 -t1 cobalt.local &> /dev/null
if [ $? -eq 0 ]; then
    DEPOT_SERVER="cobalt"
fi

ping -c1 -t1 10.1.39.179 &> /dev/null
if [ $? -eq 0 ]; then
    DEPOT_SERVER="silicon"
fi

ping -c1 -t1 aluminum &> /dev/null
if [ $? -eq 0 ]; then
    DEPOT_SERVER="aluminum"
fi

if [ -z $DEPOT_SERVER ]; then
    echo "Could not connect to a depot server."
    exit
fi

echo "Connecting to depot server $DEPOT_SERVER"

# -K :: Treat a symlinked dir on the receiving end as a dir.
# -u :: If there is a newer file on the other side, don't replace it.
CMD="rsync -avK -u --size-only $HOME/depot $DEPOT_SERVER:~/depot/"
echo $CMD

echo "============================================================"
echo "= Full transfer list of files only (no dirs)"
echo "============================================================"
echo
mkdir -p ~/.depot
$CMD -n | grep -v '/$' | tee ~/.depot/to_transfer.txt
echo
echo "See the full list of files to transfer at ~/.depot/to_transfer.txt"
echo

echo
echo "============================================================"
echo "= Transfering at least one file from each of these directories."
echo "============================================================"
$CMD -n | grep -v '/$' | grep -v '\->' | grep -v "created directory" | awk -F'/' '{print $3}' | sort | uniq | grep -v "^sec$" | grep -v "^.DS_Store$"
echo

echo
echo "============================================================"
echo "= Press enter to continue"
echo "============================================================"
echo
echo $CMD
echo

read -p ""
caffeinate -i $CMD

