#!/bin/bash


if [[ $# -ne 0 ]]; then
    echo "Usage: ./push"
    exit 0
fi
DEPOT_SERVER=""

SSID=""
if [ `uname -s` == 'Darwin' ]; then
    SSID=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | grep ' SSID' | awk -F': ' '{print $2}')
else
    echo SSID detection on linux machines not handled yet.
    exit
fi

ping -c1 -t1 cobalt.local &> /dev/null
if [ $? -eq 0 ]; then
    DEPOT_SERVER="cobalt"
fi

if [ -z $DEPOT_SERVER ]; then
    echo "Could not connect to a depot server."
    exit
fi

echo "Connecting to depot server $DEPOT_SERVER"

# -K :: Treat a symlinked dir on the receiving end as a dir.
# -u :: If there is a newer file on the other side, don't replace it.
CMD="rsync -auK -vh $HOME/depot/ $DEPOT_SERVER:~/depot/"

mkdir -p ~/.depot
# $CMD -n | grep -v '/$' | egrep -v 'building file list ... done|sent.*bytes.*received.*bytes.*bytes/sec|total size is.*speedup is|^$' > ~/.depot/to_transfer.txt
$CMD -n > ~/.depot/to_transfer.txt
echo
echo 'Press enter to review dry run output of:'
echo "  $CMD -n"
read -p ""
less ~/.depot/to_transfer.txt

echo 'Press enter to actually run:'
echo "  $CMD"

read -p ""
caffeinate -i $CMD

